// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbsCpp
NumericMatrix gibbsCpp(int N, int a, int b, int n, int burn);
RcppExport SEXP _SA24204125_gibbsCpp(SEXP NSEXP, SEXP aSEXP, SEXP bSEXP, SEXP nSEXP, SEXP burnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbsCpp(N, a, b, n, burn));
    return rcpp_result_gen;
END_RCPP
}
// RK4ODECpp
DataFrame RK4ODECpp(Function fun, double a, double b, int n, double y0);
RcppExport SEXP _SA24204125_RK4ODECpp(SEXP funSEXP, SEXP aSEXP, SEXP bSEXP, SEXP nSEXP, SEXP y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type fun(funSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type y0(y0SEXP);
    rcpp_result_gen = Rcpp::wrap(RK4ODECpp(fun, a, b, n, y0));
    return rcpp_result_gen;
END_RCPP
}
// RombergCpp
List RombergCpp(Function f, double a, double b, double TOL);
RcppExport SEXP _SA24204125_RombergCpp(SEXP fSEXP, SEXP aSEXP, SEXP bSEXP, SEXP TOLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type TOL(TOLSEXP);
    rcpp_result_gen = Rcpp::wrap(RombergCpp(f, a, b, TOL));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204125_gibbsCpp", (DL_FUNC) &_SA24204125_gibbsCpp, 5},
    {"_SA24204125_RK4ODECpp", (DL_FUNC) &_SA24204125_RK4ODECpp, 5},
    {"_SA24204125_RombergCpp", (DL_FUNC) &_SA24204125_RombergCpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204125(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
