# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title The gibbs function
#' @description A function is used in homework
#' @param N size
#' @param a the param of beta
#' @param b the param of beta
#' @param n the size of x
#' @param burn start from burn.
#' @return gibbs result
#' @examples
#' \dontrun{
#' N <- 10000
#' a <- 2
#' b <- 3
#' n <- 10
#' burn <- 1000
#' result <- gibbsCpp(N, a, b, n, burn)
#' }
#' @export
gibbsCpp <- function(N, a, b, n, burn) {
    .Call('_SA24204125_gibbsCpp', PACKAGE = 'SA24204125', N, a, b, n, burn)
}

#' @title The fourth-order Runger-Kutta method using Cpp
#' @description This model is used to calculate the initial values of ordinary differential equations
#' @param fun the ordinary differential equations
#' @param a the upper bound of the interval
#' @param b the lower bound of the interval
#' @param n the length of the interval
#' @param y0 initial value
#' @return The solution of the equation on the interval [a,b], the data type is dataframe.
#' @examples
#' \dontrun{
#' fun <- function(x,y){
#' x-y+1
#' }
#' a=0
#' b=1
#' n=10
#' y0=1
#' library(Rcpp)
#' sourceCpp(paste0('D:/R/Rwork/Statistics_computing/RK.cpp'))
#' RK4ODECpp = RK4ODECpp(fun, a, b, n, y0)
#' }
#' @export
RK4ODECpp <- function(fun, a, b, n, y0) {
    .Call('_SA24204125_RK4ODECpp', PACKAGE = 'SA24204125', fun, a, b, n, y0)
}

#' @title The Romberg quadrature method using Cpp
#' @description This method is used to solve numerical integrals
#' @param f the function
#' @param a the upper bound of the interval
#' @param b the lower bound of the interval
#' @param TOL integration error limit
#' @return A list is returned, with the first value s being the integral result, 
#' the second value R being the iterative process, and the third value k being the number of iterations
#' @examples
#' \dontrun{
#' f <- function(x) exp(x)*x^2+exp(x)*sin(x)+exp(x)*cos(x)+2**x  # 积分函数
#' a <- 0  # 积分下限
#' b <- 1  # 积分上限
#' TOL <- 1e-16  # 误差容限
#' resultCpp <- RombergCpp(f, a, b, TOL)
#' }
#' @export
RombergCpp <- function(f, a, b, TOL) {
    .Call('_SA24204125_RombergCpp', PACKAGE = 'SA24204125', f, a, b, TOL)
}

